[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RealProbe"
authors = [{name = "Jiho Kim", email = "jiho.kim@gatech.edu"}]
dynamic = ["version", "description"]
